### ISSUE TITLE
Movies do not work on Rance VI or Sengoku

### ISSUE THREAD

**Issue by TheMSnap** [nunuhara/xsystem4#110]
I was able to finish VI thanks to your last patch, but I was never able to get the opening movie working even with LAV filters installed on both Linux and Windows. Same goes for Sengoku, but it's throwing a different error. I've attached images of both.
![xsystem4bug](https://user-images.githubusercontent.com/124742847/228118636-510edbe1-d8dd-4490-bba2-1aad5bf9db8e.png)
![xsystem4bug2](https://user-images.githubusercontent.com/124742847/228118648-b6a023d3-cc8b-45f4-b2c1-b3e4e550063c.png)

**Comment by nunuhara** [comment]
The issue with Sengoku should be fixed in [alpha-4](https://github.com/nunuhara/xsystem4/releases/tag/alpha-4)
The issue with VI is specific to the English version of the game. It appears they encoded the OP movie as VC-1, whereas the original is MPEG-1. I'm not sure how much work it would be to support VC-1 video. Maybe @kichikuou can weigh in?

**Comment by kichikuou** [comment]
Basically we'll need to change `movie.c` to use FFmpeg (which should be able to decode VC-1) instead of PL_MPEG. I don't want to make FFmpeg a required dependency (because it would further complicate the Android build), so maybe make FFmpeg optional and fallback to PL_MPEG when it's not available?

I'll see if I can make a patch.

**Comment by nunuhara** [comment]
The issue with Rance VI should be fixed in [alpha-4.1](https://github.com/nunuhara/xsystem4/releases/tag/alpha-4.1)
